[package]
name = "lewdware"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
byteorder = "1.5.0"
ffmpeg-next = "8.0.0"
image = { version = "0.25.6", features = ["avif-native"] }
pixels = "0.15.0"
rand = "0.9.2"
rdev = "0.5.3"
rodio = "0.21.1"
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
softbuffer = "0.4.6"
tempfile = "3.21.0"
winit = "0.30.12"
