[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.29.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-pc-windows-msvc", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]

[dist.dependencies.apt]
build-essential = "*"
pkg-config = "*"
gcc-aarch64-linux-gnu = "*"
git = "*"
nasm = "*"
meson = "*"
ninja-build = "*"
libasound-dev = "*"
libopus-dev = "*"
libvpx-dev = "*"

[dist.dependencies.homebrew]
nasm = "*"
meson = "*"
ninja = "*"
opus = "*"
libvpx = ""

[dist.dependencies.chocolatey]
nasm = "*"
meson = "*"
ninja = "*"
