use std::{collections::HashMap, fs, path::PathBuf};

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_with::serde_as;
use uuid::Uuid;

use crate::mode::OptionValue;
use crate::schedule::ScheduleConfig;

#[serde_as]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AppConfig {
    pub pack_path: Option<PathBuf>,
    pub uploaded_modes: Vec<PathBuf>,
    pub mode: Mode,
    #[serde_as(as = "Vec<(_, _)>")]
    pub mode_options: HashMap<Mode, HashMap<String, OptionValue>>,
    /// `Mode::Experience`'s meta-control values, scoped per pack rather than globally like
    /// `mode_options` -- see `behaviour-design/default-mode.md`, Ownership: "a pacing scalar
    /// tuned for one experience is wrong for another". Keyed by the pack's own UUID (stable
    /// across saves, regenerated by "save as"/conversion); empty/missing means every option
    /// falls back to its schema default for that pack.
    #[serde_as(as = "Vec<(_, _)>")]
    #[serde(default)]
    pub experience_options: HashMap<Uuid, HashMap<String, OptionValue>>,
    pub panic_button: Key,
    pub disabled_monitors: Vec<String>,
    pub capabilities: Capabilities,
    pub volume: Volume,
    /// `design/scheduling.md`'s schedule vocabulary (windows/jitter/quiet hours) plus the
    /// grace-notification toggle. `enabled` also drives OS autostart-at-login registration
    /// one-to-one (see `config/src-tauri/src/lib.rs`'s `set_schedule_enabled`). `#[serde(default)]`
    /// is required, not polish -- every pre-existing `config.json` has no `"schedule"` key at all.
    #[serde(default)]
    pub schedule: ScheduleConfig,
}

/// Consent-critical, user-owned off-switches for actions a mode can take that reach outside its
/// own windows. Structurally out of a mode's reach (see `behaviour-design/default-mode.md`,
/// Ownership): there is no schema path from a mode or pack to these fields, only the app-level
/// config. Enforced main-thread-side; a forbidden call no-ops, returning `false` to Lua rather
/// than erroring, exactly like any other "could not do it" outcome (e.g. no browser installed).
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct Capabilities {
    pub wallpaper: bool,
    pub open_link: bool,
    pub notify: bool,
}

impl Default for Capabilities {
    fn default() -> Self {
        Self {
            wallpaper: true,
            open_link: true,
            notify: true,
        }
    }
}

/// User-owned master gain, independent per audio channel -- mirrors the engine's own two-track
/// split (`VideoWindow`'s embedded audio track vs. standalone `AudioHandle`s from
/// `lewdware.play_audio`), since packs commonly use them for different purposes (background
/// loops vs. startle-video audio) that a user may want to balance independently. Multiplies with
/// whatever per-track volume a mode requests; enforced main-thread-side, at the point a raw
/// volume value from Lua first enters `LewdwareApp` (spawn time and any later `set_volume()`
/// call) -- everything downstream only ever sees the already-scaled effective volume.
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
pub struct Volume {
    pub video: f32,
    pub audio: f32,
}

impl Default for Volume {
    fn default() -> Self {
        Self {
            video: 1.0,
            audio: 1.0,
        }
    }
}

/// Which mode runs, and where its `.lwmode` data comes from. Each variant identifies exactly one
/// mode -- there's no "which mode within the file" selector, since one `.lwmode` file is now
/// always exactly one mode (see `shared::mode::Metadata`'s doc comment). `Sandbox`/`Experience`
/// are the two engine-bundled default modes (see `behaviour-design/default-mode.md`) -- each its
/// own `.lwmode` bundle, sharing library Lua via the mode-project `include` mechanism, not one
/// bundle selected by name.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, Hash, Default)]
pub enum Mode {
    /// The engine-bundled Sandbox default mode: the user is the designer.
    #[default]
    Sandbox,
    /// The engine-bundled Experience default mode: the pack author is the designer. Its options
    /// are scoped per pack (see `AppConfig::experience_options`), not globally like every other
    /// mode's.
    Experience,
    /// A mode embedded in the loaded pack. `id` is the row id in the pack's own `modes` table
    /// (see `MediaPack::get_mode`) -- unrelated to the pack's own UUID or the mode's stable id
    /// (the latter lives in the embedded `.lwmode` blob's own header).
    Pack {
        id: u64,
    },
    File {
        path: PathBuf,
    },
}

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct Key {
    pub name: String,
    pub code: String,
    pub modifiers: Modifiers,
}

impl std::fmt::Display for Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut parts = Vec::new();
        if self.modifiers.ctrl {
            parts.push("Ctrl");
        }
        if self.modifiers.alt {
            parts.push("Alt");
        }
        if self.modifiers.shift {
            parts.push("Shift");
        }
        if self.modifiers.meta {
            parts.push("Meta");
        }
        parts.push(&self.name);
        write!(f, "{}", parts.join(" + "))
    }
}

#[derive(Clone, Serialize, Deserialize, Debug, Default, PartialEq, Eq)]
pub struct Modifiers {
    pub alt: bool,
    pub ctrl: bool,
    pub shift: bool,
    pub meta: bool,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            pack_path: None,
            uploaded_modes: Vec::new(),
            mode: Mode::default(),
            mode_options: HashMap::new(),
            experience_options: HashMap::new(),
            panic_button: Key {
                name: "Escape".to_string(),
                code: "Escape".to_string(),
                modifiers: Modifiers {
                    shift: true,
                    ..Default::default()
                },
            },
            disabled_monitors: Vec::new(),
            capabilities: Capabilities::default(),
            volume: Volume::default(),
            schedule: ScheduleConfig::default(),
        }
    }
}

pub fn load_config() -> Result<AppConfig> {
    let path = config_path()?;

    Ok(serde_json::from_str(&fs::read_to_string(path)?)?)
}

pub fn save_config(config: &AppConfig) -> Result<()> {
    let path = config_path()?;
    let temp_config_path = path.with_added_extension("tmp");

    fs::write(&temp_config_path, serde_json::to_string(config)?)?;
    fs::rename(temp_config_path, path)?;

    Ok(())
}

pub async fn save_config_async(config: AppConfig) -> Result<()> {
    let path = config_path()?;
    let temp_config_path = path.with_added_extension("tmp");

    tracing::info!("{}", temp_config_path.display());

    tokio::fs::write(
        &temp_config_path,
        tokio::task::spawn_blocking(move || serde_json::to_string(&config)).await??,
    )
    .await?;
    tokio::fs::rename(temp_config_path, path).await?;

    Ok(())
}

fn config_path() -> Result<PathBuf> {
    let mut config_path = dirs::config_dir()
        .ok_or_else(|| anyhow!("Could not find a valid config dir for this OS"))?;

    config_path.push("lewdware");

    fs::create_dir_all(&config_path)?;

    config_path.push("config.json");

    Ok(config_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn appconfig_json_roundtrip() {
        let original = AppConfig::default();
        let json = serde_json::to_string(&original).unwrap();
        let decoded: AppConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&decoded).unwrap()
        );
    }

    #[test]
    fn key_display_no_modifiers() {
        let key = Key {
            name: "Escape".to_string(),
            code: "Escape".to_string(),
            modifiers: Modifiers::default(),
        };
        assert_eq!(key.to_string(), "Escape");
    }

    #[test]
    fn key_display_with_modifiers() {
        let key = Key {
            name: "Escape".to_string(),
            code: "Escape".to_string(),
            modifiers: Modifiers {
                shift: true,
                ..Default::default()
            },
        };
        assert_eq!(key.to_string(), "Shift + Escape");
    }

    #[test]
    fn key_display_all_modifiers() {
        let key = Key {
            name: "F1".to_string(),
            code: "F1".to_string(),
            modifiers: Modifiers {
                ctrl: true,
                alt: true,
                shift: true,
                meta: true,
            },
        };
        assert_eq!(key.to_string(), "Ctrl + Alt + Shift + Meta + F1");
    }

    #[test]
    fn default_volume_is_unattenuated() {
        let config = AppConfig::default();
        assert_eq!(config.volume.video, 1.0);
        assert_eq!(config.volume.audio, 1.0);
    }

    #[test]
    fn default_capabilities_allow_everything() {
        let config = AppConfig::default();
        assert!(config.capabilities.wallpaper);
        assert!(config.capabilities.open_link);
        assert!(config.capabilities.notify);
    }

    #[test]
    fn default_panic_button_is_shift_escape() {
        let config = AppConfig::default();
        assert_eq!(config.panic_button.code, "Escape");
        assert!(config.panic_button.modifiers.shift);
        assert!(!config.panic_button.modifiers.ctrl);
    }

    #[test]
    fn default_schedule_is_disabled_and_empty() {
        let config = AppConfig::default();
        assert!(!config.schedule.enabled);
        assert!(config.schedule.windows.is_empty());
        assert!(config.schedule.quiet_hours.is_empty());
        assert!(config.schedule.grace_notification);
    }

    /// The actual risk with adding a field to `AppConfig`: every pre-existing user's
    /// `config.json` has no `"schedule"` key at all. `#[serde(default)]` must keep it loading.
    #[test]
    fn config_json_without_a_schedule_key_still_loads() {
        let json = serde_json::json!({
            "pack_path": null,
            "uploaded_modes": [],
            "mode": "Sandbox",
            "mode_options": [],
            "experience_options": [],
            "panic_button": {
                "name": "Escape",
                "code": "Escape",
                "modifiers": { "alt": false, "ctrl": false, "shift": true, "meta": false }
            },
            "disabled_monitors": [],
            "capabilities": { "wallpaper": true, "open_link": true, "notify": true },
            "volume": { "video": 1.0, "audio": 1.0 }
        });

        let config: AppConfig =
            serde_json::from_value(json).expect("should decode without a schedule key");
        assert_eq!(config.schedule, ScheduleConfig::default());
    }
}
