use std::{collections::HashMap, fs, path::PathBuf};

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_with::serde_as;
use uuid::Uuid;

use crate::mode::StoredValue;
use crate::schedule::ScheduleConfig;

#[serde_as]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AppConfig {
    pub pack_path: Option<PathBuf>,
    pub uploaded_modes: Vec<PathBuf>,
    pub mode: Mode,
    /// Values as the user left them, *not* values a mode can run on: `StoredValue`, not
    /// `OptionValue`, because what is on disk has been through JSON (and, for anything saved
    /// by `config/`, through JavaScript) and no longer knows which `OptionType` it belongs
    /// to. Read these through `mode::resolve_options` against the mode's schema.
    #[serde_as(as = "Vec<(_, _)>")]
    pub mode_options: HashMap<Mode, HashMap<String, StoredValue>>,
    /// `Mode::Experience`'s meta-control values, scoped per pack rather than globally like
    /// `mode_options` -- see `behaviour-design/default-mode.md`, Ownership: "a pacing scalar
    /// tuned for one experience is wrong for another". Keyed by the pack's own UUID (stable
    /// across saves, regenerated by "save as"/conversion); empty/missing means every option
    /// falls back to its schema default for that pack.
    #[serde_as(as = "Vec<(_, _)>")]
    #[serde(default)]
    pub experience_options: HashMap<Uuid, HashMap<String, StoredValue>>,
    /// The named window look every popup is drawn with, unless the running mode names one
    /// itself for a particular window. `design/window-themes.md`, Ownership.
    ///
    /// User-owned rather than mode-owned because the alternative leaves the user's control at
    /// the mercy of a mode author's diligence: a mode that simply never mentions themes -- the
    /// overwhelmingly common case -- would strand its user on whatever the engine defaulted to,
    /// with nothing in `config/` to change it. As a default the engine applies, doing nothing is
    /// the user-respecting thing to do, and a mode that genuinely needs a specific look (a fake
    /// Win95 error box) still names it per window, which always wins.
    ///
    /// A free-form string, not an enum: `shared` does not depend on the engine's `ThemeChoice`,
    /// and a config written against a newer engine may name a theme this one has never heard of.
    /// The engine falls back to its own default rather than refusing to load the config.
    #[serde(default = "default_theme")]
    pub theme: String,
    /// Which palette [`AppConfig::theme`] is drawn in: `"light"`, `"dark"`, or `"auto"` to
    /// follow the desktop's own setting. Same string-not-enum reasoning as `theme`.
    #[serde(default = "default_appearance")]
    pub appearance: String,
    pub stop_button: Key,
    pub disabled_monitors: Vec<String>,
    /// The sub-area of each monitor popups are confined to, keyed exactly like
    /// `disabled_monitors` (see `shared::monitor`) -- a monitor with no entry gets the whole
    /// screen. `#[serde(default)]` is required: every pre-existing `config.json` has no
    /// `"monitor_regions"` key.
    ///
    /// Deliberately separate from `disabled_monitors` rather than folded into it as a zero-area
    /// region: "don't use this screen" and "use this corner of this screen" are different
    /// answers, and a user who disables a monitor and re-enables it should get their region back,
    /// not a monitor that is on but unusable.
    #[serde(default)]
    pub monitor_regions: HashMap<String, crate::monitor::MonitorRegion>,
    pub capabilities: Capabilities,
    /// Sub-settings for the `capabilities.set_wallpaper` permission. `#[serde(default)]` is required:
    /// every pre-existing `config.json` has no `"wallpaper"` key.
    #[serde(default)]
    pub wallpaper: WallpaperConfig,
    pub volume: Volume,
    /// Which output device sounds play on. `None` -- the default, and every pre-existing
    /// `config.json` -- means the system default, which the engine re-resolves every time it opens
    /// a sink rather than pinning once, so plugging in headphones does the expected thing.
    #[serde(default)]
    pub audio_device: Option<AudioDeviceChoice>,
    /// `design/scheduling.md`'s schedule vocabulary (windows/jitter/quiet hours) plus the
    /// grace-notification toggle. `enabled` also drives OS autostart-at-login registration
    /// one-to-one (see `config/src-tauri/src/lib.rs`'s `set_schedule_enabled`). `#[serde(default)]`
    /// is required, not polish -- every pre-existing `config.json` has no `"schedule"` key at all.
    #[serde(default)]
    pub schedule: ScheduleConfig,
}

/// Consent-critical, user-owned off-switches for actions a mode can take that reach outside its
/// own windows. Structurally out of a mode's reach (see `behaviour-design/default-mode.md`,
/// Ownership): there is no schema path from a mode or pack to these fields, only the app-level
/// config. Enforced main-thread-side; a forbidden call no-ops, returning `false` to Lua rather
/// than erroring, exactly like any other "could not do it" outcome (e.g. no browser installed).
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct Capabilities {
    pub set_wallpaper: bool,
    pub open_links: bool,
    pub send_notifications: bool,
}

impl Capabilities {
    /// Whether a permission a mode declares in its schema (`shared::mode::Permission`) is
    /// currently granted. The bridge between what a mode says it uses and what the user allows.
    pub fn allows(&self, permission: crate::mode::Permission) -> bool {
        match permission {
            crate::mode::Permission::SetWallpaper => self.set_wallpaper,
            crate::mode::Permission::OpenLinks => self.open_links,
            crate::mode::Permission::SendNotifications => self.send_notifications,
        }
    }
}

impl Default for Capabilities {
    fn default() -> Self {
        Self {
            set_wallpaper: true,
            // Off by default, unlike the other two. Opening a browser tab is the one capability
            // whose effect escapes the desktop session entirely -- it can land on a screen the
            // user did not expect and does not control, and it is not undone by quitting. Modes
            // declare `needs_permissions: ["open_links"]` on the options that need it, so `config/` can
            // offer the grant in context rather than leaving the user with a dead toggle.
            open_links: false,
            send_notifications: true,
        }
    }
}

/// What to put the wallpaper back to once a pack is done with it.
///
/// Deliberately *not* platform-aware: `capabilities` has no `#[serde(default)]`, so whatever
/// `Default` returns is written to `config.json` on first save and is sticky forever after. A
/// default that depended on the desktop would be frozen from whichever machine happened to run
/// first, and would be wrong after a switch from Plasma to sway or on a synced home directory.
/// Whether the original can actually be restored is re-checked at run time instead, by
/// `shared::wallpaper::Snapshot::is_restorable`.
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq, Default)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum WallpaperRestore {
    /// Whatever it was before. Only possible on desktops that can report their own wallpaper.
    #[default]
    Original,
    /// A fixed image, for desktops that cannot. This is what makes wallpaper changes possible at
    /// all on bare compositors -- without it the engine refuses, rather than making a change it
    /// could never undo.
    Image { path: PathBuf },
}

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq, Default)]
pub struct WallpaperConfig {
    #[serde(default)]
    pub restore: WallpaperRestore,
}

impl WallpaperConfig {
    /// The image to fall back to when the desktop cannot report its current wallpaper.
    ///
    /// `None` means "restore the original", which on such a desktop means wallpaper changes are
    /// declined outright.
    pub fn fallback_image(&self) -> Option<&std::path::Path> {
        match &self.restore {
            WallpaperRestore::Original => None,
            WallpaperRestore::Image { path } => Some(path),
        }
    }
}

/// User-owned master gain, independent per audio channel -- mirrors the engine's own two-track
/// split (`VideoWindow`'s embedded audio track vs. standalone `AudioHandle`s from
/// `lewdware.play_audio`), since packs commonly use them for different purposes (background
/// loops vs. startle-video audio) that a user may want to balance independently. Multiplies with
/// whatever per-track volume a mode requests; enforced main-thread-side, at the point a raw
/// volume value from Lua first enters `LewdwareApp` (spawn time and any later `set_volume()`
/// call) -- everything downstream only ever sees the already-scaled effective volume.
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
pub struct Volume {
    pub video: f32,
    pub audio: f32,
}

impl Default for Volume {
    fn default() -> Self {
        Self {
            video: 1.0,
            audio: 1.0,
        }
    }
}

/// A chosen audio output: the id the engine resolves, plus the name it went by when it was picked.
///
/// The name is carried purely so the picker can say *which* output is missing when that output
/// isn't connected -- an id like `pulseaudio:bluez_output.F4_9D_8A_09_4E_AA.1` is not something to
/// show a user. It is never used to find a device: `id` is the identity, and a present device is
/// always labelled from the live enumeration, so a device renamed since it was chosen shows its
/// current name rather than this one.
///
/// A device that is absent when a session starts falls back to the default *for that session* and
/// keeps this setting intact, so unplugging a USB headset never silently rewrites the choice.
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct AudioDeviceChoice {
    /// `cpal::DeviceId`'s `Display` form (`host:backend-id`) -- see
    /// [`crate::audio::AudioDeviceInfo::id`].
    pub id: String,
    /// The device's name as it read when chosen. Display-only, and only when the device is absent.
    pub name: String,
}

/// Which mode runs, and where its `.lwmode` data comes from. Each variant identifies exactly one
/// mode -- there's no "which mode within the file" selector, since one `.lwmode` file is now
/// always exactly one mode (see `shared::mode::Metadata`'s doc comment). `Sandbox`/`Experience`
/// are the two engine-bundled default modes (see `behaviour-design/default-mode.md`) -- each its
/// own `.lwmode` bundle, sharing library Lua via the mode-project `include` mechanism, not one
/// bundle selected by name.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, Hash, Default)]
pub enum Mode {
    /// The engine-bundled Sandbox default mode: the user is the designer.
    #[default]
    Sandbox,
    /// The engine-bundled Experience default mode: the pack author is the designer. Its options
    /// are scoped per pack (see `AppConfig::experience_options`), not globally like every other
    /// mode's.
    Experience,
    /// A mode embedded in the loaded pack. `id` is the row id in the pack's own `modes` table
    /// (see `MediaPack::get_mode`) -- unrelated to the pack's own UUID or the mode's stable id
    /// (the latter lives in the embedded `.lwmode` blob's own header).
    Pack {
        id: u64,
    },
    File {
        path: PathBuf,
    },
}

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct Key {
    pub name: String,
    pub code: String,
    pub modifiers: Modifiers,
}

impl std::fmt::Display for Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut parts = Vec::new();
        if self.modifiers.ctrl {
            parts.push("Ctrl");
        }
        if self.modifiers.alt {
            parts.push("Alt");
        }
        if self.modifiers.shift {
            parts.push("Shift");
        }
        if self.modifiers.meta {
            parts.push("Meta");
        }
        parts.push(&self.name);
        write!(f, "{}", parts.join(" + "))
    }
}

#[derive(Clone, Serialize, Deserialize, Debug, Default, PartialEq, Eq)]
pub struct Modifiers {
    pub alt: bool,
    pub ctrl: bool,
    pub shift: bool,
    pub meta: bool,
}

/// `native` rather than the engine's own `plain`: the API default is the predictable one (a mode
/// doing arithmetic against `outer_*` gets stable metrics by naming a theme), but the *product*
/// default is the one that looks like the machine it is running on. `design/window-themes.md`,
/// Defaults.
fn default_theme() -> String {
    "native".to_string()
}

/// `auto`, for the same reason: matching the user's desktop is what a user expects, and the
/// legibility argument for a predictable `light` applies to the Lua API, where an author's own
/// `background_color` and text colours can collide with a flipped palette.
fn default_appearance() -> String {
    "auto".to_string()
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            pack_path: None,
            uploaded_modes: Vec::new(),
            mode: Mode::default(),
            mode_options: HashMap::new(),
            experience_options: HashMap::new(),
            theme: default_theme(),
            appearance: default_appearance(),
            stop_button: Key {
                name: "Escape".to_string(),
                code: "Escape".to_string(),
                modifiers: Modifiers {
                    shift: true,
                    ..Default::default()
                },
            },
            disabled_monitors: Vec::new(),
            monitor_regions: HashMap::new(),
            capabilities: Capabilities::default(),
            wallpaper: WallpaperConfig::default(),
            volume: Volume::default(),
            audio_device: None,
            schedule: ScheduleConfig::default(),
        }
    }
}

pub fn load_config() -> Result<AppConfig> {
    let path = config_path()?;

    Ok(serde_json::from_str(&fs::read_to_string(path)?)?)
}

pub fn save_config(config: &AppConfig) -> Result<()> {
    let path = config_path()?;
    let temp_config_path = path.with_added_extension("tmp");

    fs::write(&temp_config_path, serde_json::to_string(config)?)?;
    fs::rename(temp_config_path, path)?;

    Ok(())
}

pub async fn save_config_async(config: AppConfig) -> Result<()> {
    let path = config_path()?;
    let temp_config_path = path.with_added_extension("tmp");

    tracing::info!("{}", temp_config_path.display());

    tokio::fs::write(
        &temp_config_path,
        tokio::task::spawn_blocking(move || serde_json::to_string(&config)).await??,
    )
    .await?;
    tokio::fs::rename(temp_config_path, path).await?;

    Ok(())
}

fn config_path() -> Result<PathBuf> {
    let mut config_path = dirs::config_dir()
        .ok_or_else(|| anyhow!("Could not find a valid config dir for this OS"))?;

    config_path.push("lewdware");

    fs::create_dir_all(&config_path)?;

    config_path.push("config.json");

    Ok(config_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn appconfig_json_roundtrip() {
        let original = AppConfig::default();
        let json = serde_json::to_string(&original).unwrap();
        let decoded: AppConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(
            serde_json::to_value(&original).unwrap(),
            serde_json::to_value(&decoded).unwrap()
        );
    }

    #[test]
    fn key_display_no_modifiers() {
        let key = Key {
            name: "Escape".to_string(),
            code: "Escape".to_string(),
            modifiers: Modifiers::default(),
        };
        assert_eq!(key.to_string(), "Escape");
    }

    #[test]
    fn key_display_with_modifiers() {
        let key = Key {
            name: "Escape".to_string(),
            code: "Escape".to_string(),
            modifiers: Modifiers {
                shift: true,
                ..Default::default()
            },
        };
        assert_eq!(key.to_string(), "Shift + Escape");
    }

    #[test]
    fn key_display_all_modifiers() {
        let key = Key {
            name: "F1".to_string(),
            code: "F1".to_string(),
            modifiers: Modifiers {
                ctrl: true,
                alt: true,
                shift: true,
                meta: true,
            },
        };
        assert_eq!(key.to_string(), "Ctrl + Alt + Shift + Meta + F1");
    }

    #[test]
    fn default_volume_is_unattenuated() {
        let config = AppConfig::default();
        assert_eq!(config.volume.video, 1.0);
        assert_eq!(config.volume.audio, 1.0);
    }

    /// Opening a browser is the one capability whose effect leaves the desktop session, so it
    /// starts denied. Only new installs are affected: `capabilities` has no `#[serde(default)]`,
    /// so an existing `config.json` always carries the user's own answer.
    #[test]
    fn open_link_is_the_only_capability_denied_by_default() {
        let config = AppConfig::default();
        assert!(config.capabilities.set_wallpaper);
        assert!(!config.capabilities.open_links);
        assert!(config.capabilities.send_notifications);
    }

    #[test]
    fn allows_maps_each_declared_permission_to_its_toggle() {
        use crate::mode::Permission;

        let capabilities = Capabilities {
            set_wallpaper: true,
            open_links: false,
            send_notifications: true,
        };
        assert!(capabilities.allows(Permission::SetWallpaper));
        assert!(!capabilities.allows(Permission::OpenLinks));
        assert!(capabilities.allows(Permission::SendNotifications));
    }

    /// An existing user who allowed link opening keeps that answer -- the new default must not
    /// reach back into configs already on disk.
    #[test]
    fn an_existing_config_keeps_its_own_open_link_answer() {
        let json = serde_json::json!({
            "pack_path": null, "uploaded_modes": [], "mode": "Sandbox",
            "mode_options": [], "experience_options": [],
            "stop_button": {
                "name": "Escape", "code": "Escape",
                "modifiers": { "alt": false, "ctrl": false, "shift": true, "meta": false }
            },
            "disabled_monitors": [],
            "capabilities": { "set_wallpaper": true, "open_links": true, "send_notifications": true },
            "volume": { "video": 1.0, "audio": 1.0 }
        });

        let config: AppConfig = serde_json::from_value(json).unwrap();
        assert!(config.capabilities.open_links);
    }

    /// Same risk as `schedule` below, one field later: nobody's `config.json` has a
    /// `"monitor_regions"` key, and a monitor with no entry means the whole screen.
    #[test]
    fn config_json_without_monitor_regions_still_loads() {
        let json = serde_json::json!({
            "pack_path": null, "uploaded_modes": [], "mode": "Sandbox",
            "mode_options": [], "experience_options": [],
            "stop_button": {
                "name": "Escape", "code": "Escape",
                "modifiers": { "alt": false, "ctrl": false, "shift": true, "meta": false }
            },
            "disabled_monitors": [],
            "capabilities": { "set_wallpaper": true, "open_links": true, "send_notifications": true },
            "volume": { "video": 1.0, "audio": 1.0 }
        });

        let config: AppConfig =
            serde_json::from_value(json).expect("should decode without a monitor_regions key");
        assert!(config.monitor_regions.is_empty());
    }

    /// The shape the Svelte side writes, and the engine reads back.
    #[test]
    fn a_monitor_region_round_trips_by_monitor_id() {
        let mut config = AppConfig::default();
        config.monitor_regions.insert(
            "eDP-1".to_owned(),
            crate::monitor::MonitorRegion {
                x: 0.5,
                y: 0.0,
                width: 0.5,
                height: 1.0,
            },
        );

        let encoded = serde_json::to_string(&config).unwrap();
        let decoded: AppConfig = serde_json::from_str(&encoded).unwrap();

        assert_eq!(
            decoded.monitor_regions.get("eDP-1").copied(),
            config.monitor_regions.get("eDP-1").copied()
        );
    }

    #[test]
    fn default_stop_button_is_shift_escape() {
        let config = AppConfig::default();
        assert_eq!(config.stop_button.code, "Escape");
        assert!(config.stop_button.modifiers.shift);
        assert!(!config.stop_button.modifiers.ctrl);
    }

    #[test]
    fn default_schedule_is_disabled_and_empty() {
        let config = AppConfig::default();
        assert!(!config.schedule.enabled);
        assert!(config.schedule.rules.is_empty());
        assert!(config.schedule.quiet_hours.is_empty());
        assert!(config.schedule.grace_notification);
    }

    /// The actual risk with adding a field to `AppConfig`: every pre-existing user's
    /// `config.json` has no `"schedule"` key at all. `#[serde(default)]` must keep it loading.
    #[test]
    fn config_json_without_a_schedule_key_still_loads() {
        let json = serde_json::json!({
            "pack_path": null,
            "uploaded_modes": [],
            "mode": "Sandbox",
            "mode_options": [],
            "experience_options": [],
            "stop_button": {
                "name": "Escape",
                "code": "Escape",
                "modifiers": { "alt": false, "ctrl": false, "shift": true, "meta": false }
            },
            "disabled_monitors": [],
            "capabilities": { "set_wallpaper": true, "open_links": true, "send_notifications": true },
            "volume": { "video": 1.0, "audio": 1.0 }
        });

        let config: AppConfig =
            serde_json::from_value(json).expect("should decode without a schedule key");
        assert_eq!(config.schedule, ScheduleConfig::default());
    }
}

#[cfg(test)]
mod wallpaper_config_tests {
    use super::*;

    /// Every pre-existing `config.json` predates this field, so a config without it must still
    /// load -- and must load as "restore the original", not as some half-set image.
    #[test]
    fn config_without_a_wallpaper_key_still_loads() {
        let json = r#"{
            "pack_path": null, "uploaded_modes": [], "mode": "Sandbox",
            "mode_options": [], "stop_button": {"name":"Escape","code":"Escape",
            "modifiers":{"alt":false,"ctrl":false,"shift":false,"meta":false}},
            "disabled_monitors": [],
            "capabilities": {"set_wallpaper": true, "open_links": true, "send_notifications": true},
            "volume": {"video": 1.0, "audio": 1.0}
        }"#;

        let config: AppConfig = serde_json::from_str(json).unwrap();
        assert_eq!(config.wallpaper.restore, WallpaperRestore::Original);
        assert_eq!(config.wallpaper.fallback_image(), None);
    }

    /// The shape the Svelte `WallpaperRestore` union has to match.
    #[test]
    fn restore_target_serialises_as_a_tagged_union() {
        let original = serde_json::to_string(&WallpaperRestore::Original).unwrap();
        assert_eq!(original, r#"{"kind":"original"}"#);

        let image = serde_json::to_string(&WallpaperRestore::Image {
            path: PathBuf::from("/a/b.png"),
        })
        .unwrap();
        assert_eq!(image, r#"{"kind":"image","path":"/a/b.png"}"#);
    }

    #[test]
    fn a_chosen_image_is_offered_as_the_fallback() {
        let config = WallpaperConfig {
            restore: WallpaperRestore::Image {
                path: PathBuf::from("/a/b.png"),
            },
        };
        assert_eq!(
            config.fallback_image(),
            Some(std::path::Path::new("/a/b.png"))
        );
    }
}
